package:
  name: ComexDown
  version: 0.8

requirements:
  build:
    - python>=3.7
  run:
    - python>=3.7

about:
  home: https://bitbucket.org/DanKKom/comexdown/
  license: The MIT License
  summary:
    A little CLI utility in Python to download Brazil's foreign trade data 
    published by MDIC.
